<?php

namespace Kuroneko\Rbac\Exceptions;

use App\Exceptions\Handler as HandlerException;
use Exception;
use Illuminate\Auth\AuthenticationException;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;

class Handler extends HandlerException
{
    public function render($request, Exception $exception)
    {
        if ($exception instanceof HttpException) {
            $code = $exception->getStatusCode();
            switch ($code) {
                case 403:
                {
                    return response(view('rbac::access-denie'), 403);
                }
                case 404:{
                    return response(view('ttct::errors.404'), 404);
                }
            }
        }
        return parent::render($request, $exception);
    }

    protected function unauthenticated($request, AuthenticationException $exception)
    {
        return parent::unauthenticated($request, $exception); // TODO: Change the autogenerated stub
    }
}
